In [1]:
import itertools
import json
import numpy as np
from hmmlearn import hmm
from models_gaussian import StandardGaussianHMM, GaussianDenseHMM
import time
from tqdm import tqdm
import ssm
from ssm.util import find_permutation

np.random.seed(2022)

2022-07-27 10:27:11.104344: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-07-27 10:27:11.104425: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


Instructions for updating:
non-resource variables are not supported in the long term


In [2]:
# ssm_hmm = ssm.HMM(n, 1, observations="categorical")
# ssm_hmm.observations.__init__(K=n, D=1, C=n_features)
# ssm_hmm.fit(X_true)
#
# most_likely_states = ssm_hmm.most_likely_states(X_true)
# ssm_hmm.permute(find_permutation(Y_true, most_likely_states))
# print(ssm_hmm.transitions.transition_matrix.round(2))
#
# (ssm_hmm.most_likely_states(X_true) == Y_true).mean()

In [2]:
def prepare_params(n, A_stat=False):
    pi = np.random.uniform(size=n)
    pi /= pi.sum()
    if A_stat:
        A = np.repeat(pi[np.newaxis,:], n, axis=0)
    else:
        A = np.exp(np.random.uniform(0, 5, size=(n, n)))
        A /= A.sum(axis=1)[:, np.newaxis]

    mu = np.random.randint(-10, 10, size=n)
    sigma = np.random.uniform(0.1,  1.5, size=n)
    return pi, A, mu, sigma


def my_hmm_sampler(pi, A,  mu, sigma, T):  # TODO
    n = pi.shape[0]
    X = [np.random.choice(np.arange(n), 1, replace=True, p=pi)]
    for t in range(T - 1):
        X.append(np.random.choice(np.arange(n), 1, replace=True, p=A[X[t][0], :]))
    Y = np.concatenate([np.random.normal(mu[s[0]], sigma[s[0]], 1) for s in X]).reshape(-1, 1)
    return X, Y


def experiment(n, m, T, s,  l, A_stat=False):
    pi, A, mu, sigma = prepare_params(n, A_stat)
    data = [my_hmm_sampler(pi, A, mu, sigma, T) for _ in range(s)]
    X_true = np.concatenate([x[1] for x in data])
    lenghts = [len(x[1]) for x in data]
    Y_true = np.concatenate([np.concatenate(y[0]) for y in data])
    print(X_true.shape)
    standard_acc = []
    standard_timer = []
    dense_acc = []
    dense_timer = []
    hmml_acc = []
    hmml_timer = []
    for _ in tqdm(range(3), desc="HMM"):
        # A_init = np.exp(np.random.uniform(0, 5, size=(n, n)))
        # A_init /= A_init.sum(axis=1)[:, np.newaxis]

        # start = time.perf_counter()
        # standardhmm = StandardGaussianHMM(n, em_iter=100, covariance_type='diag')
        # # standardhmm.transmat_ = A_init
        # standardhmm.fit(X_true, lenghts)
        # preds = np.concatenate([standardhmm.predict(x[1]) for x in data])
        # standard_timer.append(time.perf_counter() - start)
        # perm = find_permutation(preds, Y_true)
        # standard_acc.append((Y_true == np.array([perm[i] for i in preds])).mean())

        start = time.perf_counter()
        densehmm = GaussianDenseHMM(n, init_params="se",  mstep_config={"l_uz":  l, "l_vw": l}, covariance_type='full', em_iter=20)
        # densehmm.transmat_ = A_init
        densehmm.fit(X_true, lenghts)
        preds = np.concatenate([densehmm.predict(x[1]) for x in data])
        perm = find_permutation(preds, Y_true)
        dense_timer.append(time.perf_counter() - start)
        dense_acc.append((Y_true == np.array([perm[i] for i in preds])).mean())

        start = time.perf_counter()
        hmml = hmm.GaussianHMM(n, n_iter=100, init_params="s", covariance_type='full')
        # hmml.transmat_ = A_init
        hmml.fit(X_true, lenghts)
        preds = np.concatenate([hmml.predict(x[1]) for x in data])
        hmml_timer.append(time.perf_counter() - start)
        perm = find_permutation(preds, Y_true)
        hmml_acc.append((Y_true == np.array([perm[i] for i in preds])).mean())

    return {"standard_acc": standard_acc,
            "standard_time":  standard_timer,
            # "ssm_acc": ssm_acc,
            # "ssm_time":  ssm_time,
            "dense_acc": dense_acc,
            "dense_time": dense_timer,
            "hmml_acc": hmml_acc,
            "hmml_time": hmml_timer,
            "pi": pi,
            "A": A,
            "mu": mu,
            "sigma": sigma}


def run_experiments():
    results = []
    for  n, v, T, A_stat, l in itertools.product([2, 3, 4, 8],  [5, 10, 20], [10, 100, 1000],  [True, False],  [3,  4,  5]):
        tmp = experiment(n, v, T, 100, l, A_stat)
        results.append({**tmp, "n": n,  "v":  v, "T": T,  "A_stat": A_stat})
    return results

In [9]:
res_tmp = experiment(3,  5, 7, 8,  3, True)

(56, 1)


Fit model:   0%|                                                                                                                                                                    | 0/20 [00:00<?, ?it/s]

[[-1.87345582]
 [-1.3567729 ]
 [ 7.85496022]
 [-1.82839369]
 [ 7.02108315]
 [-1.23206356]
 [-0.86160177]]
(7, 1)
[[[22.01548722]]

 [[22.01548722]]

 [[22.01548722]]]
[[-7.33090193]
 [-1.0654756 ]
 [ 7.03192772]]
[[-0.98973823]
 [-0.79030296]
 [-0.52119322]
 [-1.26007697]
 [-2.13049329]
 [-0.91291899]
 [ 6.4045555 ]]
(7, 1)
[[[22.01548722]]

 [[22.01548722]]

 [[22.01548722]]]
[[-7.33090193]
 [-1.0654756 ]
 [ 7.03192772]]
[[-1.82750464]
 [-1.56041956]
 [-1.63605806]
 [-0.60528458]
 [-1.51682826]
 [-1.31446494]
 [-1.34209656]]
(7, 1)
[[[22.01548722]]

 [[22.01548722]]

 [[22.01548722]]]
[[-7.33090193]
 [-1.0654756 ]
 [ 7.03192772]]
[[-1.24947708]
 [ 5.00654833]
 [ 7.08869017]
 [-5.14216167]
 [-9.18718354]
 [ 6.57960094]
 [-6.79793569]]
(7, 1)
[[[22.01548722]]

 [[22.01548722]]

 [[22.01548722]]]
[[-7.33090193]
 [-1.0654756 ]
 [ 7.03192772]]
[[-7.24846813]
 [ 8.60814797]
 [-0.60699331]
 [ 7.29002797]
 [-1.95398524]
 [ 7.01100108]
 [ 7.17553396]]
(7, 1)
[[[22.01548722]]

 [[22.01548722]]


/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:892: RuntimeWarning: divide by zero encountered in true_divide
  _covars_ = ((covars_prior + c_n) /

Fit model:   5%|███████▊                                                                                                                                                    | 1/20 [00:00<00:16,  1.12it/s]

Loss at epoch 0 is 65.97370065
Loss at epoch 1 is 56.04595116
Loss at epoch 2 is 38.68493465
Loss at epoch 3 is 8.96047798
Loss at epoch 4 is -42.66569076
Loss at epoch 5 is -128.40850149
Loss at epoch 6 is -272.29458728
Loss at epoch 7 is -501.32942899
Loss at epoch 8 is -869.57866966
Loss at epoch 9 is -1556.43133381
[[-1.87345582]
 [-1.3567729 ]
 [ 7.85496022]
 [-1.82839369]
 [ 7.02108315]
 [-1.23206356]
 [-0.86160177]]
(7, 1)
[[[22.01548722]]

 [[22.01548722]]

 [[22.01548722]]]
[[0.]
 [0.]
 [0.]]
[[-0.98973823]
 [-0.79030296]
 [-0.52119322]
 [-1.26007697]
 [-2.13049329]
 [-0.91291899]
 [ 6.4045555 ]]
(7, 1)
[[[22.01548722]]

 [[22.01548722]]

 [[22.01548722]]]
[[0.]
 [0.]
 [0.]]
[[-1.82750464]
 [-1.56041956]
 [-1.63605806]
 [-0.60528458]
 [-1.51682826]
 [-1.31446494]
 [-1.34209656]]
(7, 1)
[[[22.01548722]]

 [[22.01548722]]

 [[22.01548722]]]
[[0.]
 [0.]
 [0.]]
[[-1.24947708]
 [ 5.00654833]
 [ 7.08869017]
 [-5.14216167]
 [-9.18718354]
 [ 6.57960094]
 [-6.79793569]]
(7, 1)
[[[22.01

/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:892: RuntimeWarning: divide by zero encountered in true_divide
  _covars_ = ((covars_prior + c_n) /
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:954: RuntimeWarning: divide by zero encountered in log
  log_A = np.log(self.transmat_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:957: RuntimeWarning: divide by zero encountered in log
  log_pi = np.log(self.startprob_)

Fit model:  10%|███████████████▌                                                                                                                                            | 2/20 [00:01<00:08,  2.19it/s]/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:954: RuntimeWarning: divide by zero encountered in log
  log_A = np.log(self.transmat_)
/z

(8, 7, 3)
(8, 7, 3)
[[0.00000000e+000 1.00000000e+000 0.00000000e+000]
 [0.00000000e+000 1.00000000e+000 4.88573774e-201]
 [0.00000000e+000 1.00000000e+000 4.88573774e-201]
 [0.00000000e+000 1.00000000e+000 4.88573774e-201]
 [0.00000000e+000 1.00000000e+000 4.88573774e-201]
 [0.00000000e+000 1.00000000e+000 4.88573774e-201]
 [0.00000000e+000 1.00000000e+000 4.88573774e-201]]
[[0.00000000e+000 1.00000000e+000 0.00000000e+000]
 [0.00000000e+000 1.00000000e+000 4.88573774e-201]
 [0.00000000e+000 1.00000000e+000 4.88573774e-201]
 [0.00000000e+000 1.00000000e+000 4.88573774e-201]
 [0.00000000e+000 1.00000000e+000 4.88573774e-201]
 [0.00000000e+000 1.00000000e+000 4.88573774e-201]
 [0.00000000e+000 1.00000000e+000 4.88573774e-201]]
[[0.00000000e+000 1.00000000e+000 0.00000000e+000]
 [0.00000000e+000 1.00000000e+000 4.88573774e-201]
 [0.00000000e+000 1.00000000e+000 4.88573774e-201]
 [0.00000000e+000 1.00000000e+000 4.88573774e-201]
 [0.00000000e+000 1.00000000e+000 4.88573774e-201]
 [0.00000

/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:954: RuntimeWarning: divide by zero encountered in log
  log_A = np.log(self.transmat_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:957: RuntimeWarning: divide by zero encountered in log
  log_pi = np.log(self.startprob_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:892: RuntimeWarning: divide by zero encountered in true_divide
  _covars_ = ((covars_prior + c_n) /
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:954: RuntimeWarning: divide by zero encountered in log
  log_A = np.log(self.transmat_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:957: RuntimeWarning: divide by zero encountered in log
  log_pi = np.log(self.startprob_)

Fit mode

[[-7.24846813]
 [ 8.60814797]
 [-0.60699331]
 [ 7.29002797]
 [-1.95398524]
 [ 7.01100108]
 [ 7.17553396]]
(7, 1)
[[[22.01548722]]

 [[22.01548722]]

 [[22.01548722]]]
[[0.]
 [0.]
 [0.]]
[[-1.09713147]
 [ 7.48857674]
 [-0.13672663]
 [-1.22131061]
 [ 0.25887364]
 [ 0.39231698]
 [ 6.64762793]]
(7, 1)
[[[22.01548722]]

 [[22.01548722]]

 [[22.01548722]]]
[[0.]
 [0.]
 [0.]]
[[-0.32663715]
 [ 5.51725098]
 [ 7.04671163]
 [-7.86424793]
 [ 7.76965919]
 [ 8.06176226]
 [ 6.97103327]]
(7, 1)
[[[22.01548722]]

 [[22.01548722]]

 [[22.01548722]]]
[[0.]
 [0.]
 [0.]]
[[-2.05603541]
 [-0.35187864]
 [-0.02752231]
 [-7.74541464]
 [-1.07828821]
 [-2.59434903]
 [ 0.44811754]]
(7, 1)
[[[22.01548722]]

 [[22.01548722]]

 [[22.01548722]]]
[[0.]
 [0.]
 [0.]]
(8, 7, 3)
(8, 7, 3)
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0

/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:954: RuntimeWarning: divide by zero encountered in log
  log_A = np.log(self.transmat_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:957: RuntimeWarning: divide by zero encountered in log
  log_pi = np.log(self.startprob_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:892: RuntimeWarning: divide by zero encountered in true_divide
  _covars_ = ((covars_prior + c_n) /
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:954: RuntimeWarning: divide by zero encountered in log
  log_A = np.log(self.transmat_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:957: RuntimeWarning: divide by zero encountered in log
  log_pi = np.log(self.startprob_)

Fit mode

[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]
(8, 7, 3)
(8, 7, 3)
[[0.]
 [0.]
 [0.]]
Loss at epoch 0 is -25136964325738802140831285248.00000000
Loss at epoch 1 is -178358326535601272242445484032.00000000
Loss at epoch 2 is -1276682738768802432359507951616.00000000
Loss at epoch 3 is -9120655973439344080158915035136.00000000
Loss at epoch 4 is -65113543214975500804423310901248.00000000
Loss at epoch 5 is -464965390458531010508228908810240.00000000


/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:957: RuntimeWarning: divide by zero encountered in log
  log_pi = np.log(self.startprob_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:892: RuntimeWarning: divide by zero encountered in true_divide
  _covars_ = ((covars_prior + c_n) /
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:954: RuntimeWarning: divide by zero encountered in log
  log_A = np.log(self.transmat_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:957: RuntimeWarning: divide by zero encountered in log
  log_pi = np.log(self.startprob_)

Fit model:  35%|██████████████████████████████████████████████████████▌                                                                                                     | 7/20 [00:01<00:02,  5.70it/s]

(8, 7, 3)
(8, 7, 3)
[[0.]
 [0.]
 [0.]]
Loss at epoch 0 is -12190326545337707892213841381837242368.00000000
Loss at epoch 1 is -104831203435987862962416728378770980864.00000000
Loss at epoch 2 is -907076383609752880234978713306595852288.00000000
Loss at epoch 3 is -7839622971783120729196077325985905639424.00000000
Loss at epoch 4 is -67725085635488711576013870221021002334208.00000000
Loss at epoch 5 is -585124152571669654162767224494565860835328.00000000
Loss at epoch 6 is -5056008610422136869485069167284358416957440.00000000
Loss at epoch 7 is -43684915313125568771705894523623830403940352.00000000
Loss at epoch 8 is -377450273709662536837563749128341860577705984.00000000
Loss at epoch 9 is -3261289416358146228732837968646370942968135680.00000000
[[-1.87345582]
 [-1.3567729 ]
 [ 7.85496022]
 [-1.82839369]
 [ 7.02108315]
 [-1.23206356]
 [-0.86160177]]
(7, 1)
[[[22.01548722]]

 [[22.01548722]]

 [[22.01548722]]]
[[0.]
 [0.]
 [0.]]
[[-0.98973823]
 [-0.79030296]
 [-0.52119322]
 [-1.26007697

/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:954: RuntimeWarning: divide by zero encountered in log
  log_A = np.log(self.transmat_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:957: RuntimeWarning: divide by zero encountered in log
  log_pi = np.log(self.startprob_)

Fit model:  40%|██████████████████████████████████████████████████████████████▍                                                                                             | 8/20 [00:01<00:02,  5.87it/s]/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:954: RuntimeWarning: divide by zero encountered in log
  log_A = np.log(self.transmat_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:957: RuntimeWarning: divide by zero encountered in log
  log_pi = np.log(self.startprob_)
/ziob/klaudi

(8, 7, 3)
(8, 7, 3)
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]
(8, 7, 3)
(8, 7, 3)
[[0.]
 [0.]
 [0.]]
Loss at epoch 0 is -662965234151343652940383526039806885220915707487807602688.00000000
Loss at epoch 1 is -7968375351360231038261043292501150396161953312117784313856.00000000
Loss at epoch 2 is -96091414847177695428076028068191785486203193247659043323904.000000

/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:892: RuntimeWarning: divide by zero encountered in true_divide
  _covars_ = ((covars_prior + c_n) /
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:954: RuntimeWarning: divide by zero encountered in log
  log_A = np.log(self.transmat_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:957: RuntimeWarning: divide by zero encountered in log
  log_pi = np.log(self.startprob_)

Fit model:  50%|█████████████████████████████████████████████████████████████████████████████▌                                                                             | 10/20 [00:02<00:01,  6.85it/s]/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:954: RuntimeWarning: divide by zero encountered in log
  log_A = np.log(self.transmat_)
/z

Loss at epoch 8 is -79598692886975512035348943451707315080621352656703631685067706444714407362560.00000000
Loss at epoch 9 is -1111625649697541706728214031280286729375354898915645338553196712043575894867968.00000000
[[-1.87345582]
 [-1.3567729 ]
 [ 7.85496022]
 [-1.82839369]
 [ 7.02108315]
 [-1.23206356]
 [-0.86160177]]
(7, 1)
[[[22.01548722]]

 [[22.01548722]]

 [[22.01548722]]]
[[0.]
 [0.]
 [0.]]
[[-0.98973823]
 [-0.79030296]
 [-0.52119322]
 [-1.26007697]
 [-2.13049329]
 [-0.91291899]
 [ 6.4045555 ]]
(7, 1)
[[[22.01548722]]

 [[22.01548722]]

 [[22.01548722]]]
[[0.]
 [0.]
 [0.]]
[[-1.82750464]
 [-1.56041956]
 [-1.63605806]
 [-0.60528458]
 [-1.51682826]
 [-1.31446494]
 [-1.34209656]]
(7, 1)
[[[22.01548722]]

 [[22.01548722]]

 [[22.01548722]]]
[[0.]
 [0.]
 [0.]]
[[-1.24947708]
 [ 5.00654833]
 [ 7.08869017]
 [-5.14216167]
 [-9.18718354]
 [ 6.57960094]
 [-6.79793569]]
(7, 1)
[[[22.01548722]]

 [[22.01548722]]

 [[22.01548722]]]
[[0.]
 [0.]
 [0.]]
[[-7.24846813]
 [ 8.60814797]
 [-0.60699

/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:954: RuntimeWarning: divide by zero encountered in log
  log_A = np.log(self.transmat_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:957: RuntimeWarning: divide by zero encountered in log
  log_pi = np.log(self.startprob_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:892: RuntimeWarning: divide by zero encountered in true_divide
  _covars_ = ((covars_prior + c_n) /
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:954: RuntimeWarning: divide by zero encountered in log
  log_A = np.log(self.transmat_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:957: RuntimeWarning: divide by zero encountered in log
  log_pi = np.log(self.startprob_)

Fit mode

[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]
(8, 7, 3)
(8, 7, 3)
[[0.]
 [0.]
 [0.]]
Loss at epoch 0 is -27023561750313640802241924415556090411018075524035053546592387550209902358535475201734344704.00000000
Loss at epoch 1 is -491487221968782390611756602249623019655246737764163364949604144001790323420187510033289838592.00000000
Loss at epoch 2 is -8952327566461298736966308739683063384905837805233151634286648769044583852669822561686273392640.00000000
Loss at epoch 3 is -163041284369534373333593378522978526809091456404332765127956009035064265219481576574374073335808.00000000
Loss at epoch 4 is -2969107330748858981529634225188233141565493056252507969955359522727372315606931879833376126926848.00000000
Loss at epoch 5 is -54069690905345839844563892472365937570331790503193737928828450934411930563745824921847435255349248.00000000
Loss at epoch 6 is -984674132283934663746359998169200706581632710902044688122551437180380646679928727172421024682606592.000000

/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:892: RuntimeWarning: divide by zero encountered in true_divide
  _covars_ = ((covars_prior + c_n) /
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:954: RuntimeWarning: divide by zero encountered in log
  log_A = np.log(self.transmat_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:957: RuntimeWarning: divide by zero encountered in log
  log_pi = np.log(self.startprob_)

Fit model:  65%|████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                      | 13/20 [00:02<00:00,  7.06it/s]/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:954: RuntimeWarning: divide by zero encountered in log
  log_A = np.log(self.transmat_)
/z

(8, 7, 3)
(8, 7, 3)
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
(8, 7, 3)
(8, 7, 3)
[[0.]
 [0.]
 [0.]]
Loss at epoch 0 is -2139465066412708988866756800548591292137278373245385934884013951068211591492012445332134361063773482231460951568154624.00000000
Loss at epoch 1 is -492014409284409879696856562501835500686555858956836746115599463932533131879529814709100749501

/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:954: RuntimeWarning: divide by zero encountered in log
  log_A = np.log(self.transmat_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:957: RuntimeWarning: divide by zero encountered in log
  log_pi = np.log(self.startprob_)

Fit model:  75%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                      | 15/20 [00:02<00:00,  7.24it/s]/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:954: RuntimeWarning: divide by zero encountered in log
  log_A = np.log(self.transmat_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:957: RuntimeWarning: divide by zero encountered in log
  log_pi = np.log(self.startprob_)
/ziob/klaudi

Loss at epoch 1 is -2727802040037397202502121777219015627122185616230605223831491957982824990667513133828428441953725739014148077614056372367146436526080.00000000
Loss at epoch 2 is -69919500874127080894712523682393542767200205931186770445187590360036382420524478844970798065037816106155593166445633089886375060176896.00000000
Loss at epoch 3 is -1792092381441284157436253223619989556657935348118669124814558934299222951366714502783100473293142156927493929219447490628218338005745664.00000000
Loss at epoch 4 is -45931288316060595260308242361675951000369996038812428020291842263307006058602263352834613891535096725299561203906955903376440393226780672.00000000
Loss at epoch 5 is -1177216038399462904919158424514336041822666313862602819350111212290085978940597940704210303204998981196988098061939929045065871988006846464.00000000
Loss at epoch 6 is -30172259463058302772105060470902283266816797483678285577878302386311644460541705416613885963408889386533801088600324351726269002767644229632.00000000
L

/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:954: RuntimeWarning: divide by zero encountered in log
  log_A = np.log(self.transmat_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:957: RuntimeWarning: divide by zero encountered in log
  log_pi = np.log(self.startprob_)

Fit model:  80%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                               | 16/20 [00:02<00:00,  7.21it/s]/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:954: RuntimeWarning: divide by zero encountered in log
  log_A = np.log(self.transmat_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:957: RuntimeWarning: divide by zero encountered in log
  log_pi = np.log(self.startprob_)
/ziob/klaudi

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
(8, 7, 3)
(8, 7, 3)
[[0.]
 [0.]
 [0.]]
Loss at epoch 0 is -6117078818866570333813690045046879412570464671809454236878727176154935707658503464146912974497953257513224585253545043872982385736491007625404108994815069257728.00000000
Loss at epoch 1 is -19124619775601703704372470861430457768128205704061342634201820547418962

/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:954: RuntimeWarning: divide by zero encountered in log
  log_A = np.log(self.transmat_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:957: RuntimeWarning: divide by zero encountered in log
  log_pi = np.log(self.startprob_)

Fit model:  90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌               | 18/20 [00:03<00:00,  7.44it/s]/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:954: RuntimeWarning: divide by zero encountered in log
  log_A = np.log(self.transmat_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:957: RuntimeWarning: divide by zero encountered in log
  log_pi = np.log(self.startprob_)
/ziob/klaudi

(8, 7, 3)
(8, 7, 3)
[[0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]
[[0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]
[[0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]
[[0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]
[[0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]
[[0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]
[[0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]
[[0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]
(8, 7, 3)
(8, 7, 3)
[[0.]
 [0.]
 [0.]]
Loss at epoch 0 is -16638595405365330684087993387412008592821900618346127299402031976224563503398537923028071712624772994230243202090324683891706877326505805972472034376749253719771631246887671831304632201641984.00000000
Loss at epoch 1 is -62361348701619548381

/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:954: RuntimeWarning: divide by zero encountered in log
  log_A = np.log(self.transmat_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:957: RuntimeWarning: divide by zero encountered in log
  log_pi = np.log(self.startprob_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:892: RuntimeWarning: divide by zero encountered in true_divide
  _covars_ = ((covars_prior + c_n) /
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:954: RuntimeWarning: divide by zero encountered in log
  log_A = np.log(self.transmat_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:957: RuntimeWarning: divide by zero encountered in log
  log_pi = np.log(self.startprob_)

Fit mode

(8, 7, 3)
(8, 7, 3)
[[0.]
 [0.]
 [0.]]
Loss at epoch 0 is -104655941608120241991134712063892799084358252796291329437278994068308107923524209009770733253968060612290746102939020721144712121485338441831191719248928457544801257632491083662031419094373732725093994332160.00000000
Loss at epoch 1 is -4269904469601706253604329746594283333371953208676016542278185638504885546712954554170367290801798718849553010276397284762838784476442100156456373441342080472195227308511323679246369225185931556870427024293888.00000000
Loss at epoch 2 is -174264424394653701750558388776598315330551044122214123536254361758008378577609600773461401273014330778339444514383524054421485871950139424119000950549470531250511837856537724643707739158800200779697804541952000.00000000
Loss at epoch 3 is -7112023743112919344411704536478809493945482121163921193954779787400802034414663774182282069966730278477526732132151290259165991617454915002048126794553987819094420408517571143490675649206795255892711870677647360.00000000
Loss 

Fit model:   0%|                                                                                                                                                                    | 0/20 [00:00<?, ?it/s]

[[-1.87345582]
 [-1.3567729 ]
 [ 7.85496022]
 [-1.82839369]
 [ 7.02108315]
 [-1.23206356]
 [-0.86160177]]
(7, 1)
[[[22.01548722]]

 [[22.01548722]]

 [[22.01548722]]]
[[-1.0654756 ]
 [ 7.03192772]
 [-7.33090193]]
[[-0.98973823]
 [-0.79030296]
 [-0.52119322]
 [-1.26007697]
 [-2.13049329]
 [-0.91291899]
 [ 6.4045555 ]]
(7, 1)
[[[22.01548722]]

 [[22.01548722]]

 [[22.01548722]]]
[[-1.0654756 ]
 [ 7.03192772]
 [-7.33090193]]
[[-1.82750464]
 [-1.56041956]
 [-1.63605806]
 [-0.60528458]
 [-1.51682826]
 [-1.31446494]
 [-1.34209656]]
(7, 1)
[[[22.01548722]]

 [[22.01548722]]

 [[22.01548722]]]
[[-1.0654756 ]
 [ 7.03192772]
 [-7.33090193]]
[[-1.24947708]
 [ 5.00654833]
 [ 7.08869017]
 [-5.14216167]
 [-9.18718354]
 [ 6.57960094]
 [-6.79793569]]
(7, 1)
[[[22.01548722]]

 [[22.01548722]]

 [[22.01548722]]]
[[-1.0654756 ]
 [ 7.03192772]
 [-7.33090193]]
[[-7.24846813]
 [ 8.60814797]
 [-0.60699331]
 [ 7.29002797]
 [-1.95398524]
 [ 7.01100108]
 [ 7.17553396]]
(7, 1)
[[[22.01548722]]

 [[22.01548722]]


/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:892: RuntimeWarning: divide by zero encountered in true_divide
  _covars_ = ((covars_prior + c_n) /

Fit model:   5%|███████▊                                                                                                                                                    | 1/20 [00:00<00:17,  1.11it/s]

Loss at epoch 0 is 68.69093815
Loss at epoch 1 is 53.97636911
Loss at epoch 2 is 34.64660862
Loss at epoch 3 is 2.81138094
Loss at epoch 4 is -51.19173974
Loss at epoch 5 is -143.13313093
Loss at epoch 6 is -294.15082551
Loss at epoch 7 is -535.10766519
Loss at epoch 8 is -952.37444370
Loss at epoch 9 is -1678.57685774
[[-1.87345582]
 [-1.3567729 ]
 [ 7.85496022]
 [-1.82839369]
 [ 7.02108315]
 [-1.23206356]
 [-0.86160177]]
(7, 1)
[[[22.01548722]]

 [[22.01548722]]

 [[22.01548722]]]
[[0.]
 [0.]
 [0.]]
[[-0.98973823]
 [-0.79030296]
 [-0.52119322]
 [-1.26007697]
 [-2.13049329]
 [-0.91291899]
 [ 6.4045555 ]]
(7, 1)
[[[22.01548722]]

 [[22.01548722]]

 [[22.01548722]]]
[[0.]
 [0.]
 [0.]]
[[-1.82750464]
 [-1.56041956]
 [-1.63605806]
 [-0.60528458]
 [-1.51682826]
 [-1.31446494]
 [-1.34209656]]
(7, 1)
[[[22.01548722]]

 [[22.01548722]]

 [[22.01548722]]]
[[0.]
 [0.]
 [0.]]
[[-1.24947708]
 [ 5.00654833]
 [ 7.08869017]
 [-5.14216167]
 [-9.18718354]
 [ 6.57960094]
 [-6.79793569]]
(7, 1)
[[[22.01

/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:892: RuntimeWarning: divide by zero encountered in true_divide
  _covars_ = ((covars_prior + c_n) /
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:957: RuntimeWarning: divide by zero encountered in log
  log_pi = np.log(self.startprob_)

Fit model:  10%|███████████████▌                                                                                                                                            | 2/20 [00:01<00:08,  2.16it/s]/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:957: RuntimeWarning: divide by zero encountered in log
  log_pi = np.log(self.startprob_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:892: RuntimeWarning: divide by zero encountered in true_divide
  _covars_ = ((covars_pri

(8, 7, 3)
(8, 7, 3)
[[0.00000000e+000 1.00000000e+000 0.00000000e+000]
 [2.76913036e-262 1.00000000e+000 2.60566655e-101]
 [2.57740682e-101 1.00000000e+000 2.63206431e-101]
 [2.60351829e-101 1.00000000e+000 2.63233174e-101]
 [2.60378282e-101 1.00000000e+000 2.63233445e-101]
 [2.60378550e-101 1.00000000e+000 2.63233448e-101]
 [2.60378553e-101 1.00000000e+000 2.63233448e-101]]
[[0.00000000e+000 1.00000000e+000 0.00000000e+000]
 [2.76913036e-262 1.00000000e+000 2.60566655e-101]
 [2.57740682e-101 1.00000000e+000 2.63206431e-101]
 [2.60351829e-101 1.00000000e+000 2.63233174e-101]
 [2.60378282e-101 1.00000000e+000 2.63233445e-101]
 [2.60378550e-101 1.00000000e+000 2.63233448e-101]
 [2.60378553e-101 1.00000000e+000 2.63233448e-101]]
[[0.00000000e+000 1.00000000e+000 0.00000000e+000]
 [2.76913036e-262 1.00000000e+000 2.60566655e-101]
 [2.57740682e-101 1.00000000e+000 2.63206431e-101]
 [2.60351829e-101 1.00000000e+000 2.63233174e-101]
 [2.60378282e-101 1.00000000e+000 2.63233445e-101]
 [2.60378

/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:954: RuntimeWarning: divide by zero encountered in log
  log_A = np.log(self.transmat_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:957: RuntimeWarning: divide by zero encountered in log
  log_pi = np.log(self.startprob_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:892: RuntimeWarning: divide by zero encountered in true_divide
  _covars_ = ((covars_prior + c_n) /
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:954: RuntimeWarning: divide by zero encountered in log
  log_A = np.log(self.transmat_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:957: RuntimeWarning: divide by zero encountered in log
  log_pi = np.log(self.startprob_)

Fit mode

(8, 7, 3)
(8, 7, 3)
[[0.]
 [0.]
 [0.]]
Loss at epoch 0 is -72478155690708.12500000
Loss at epoch 1 is -325787694174053.62500000
Loss at epoch 2 is -1493786910736732.50000000
Loss at epoch 3 is -6804474100995934.00000000
Loss at epoch 4 is -30944421886131664.00000000
Loss at epoch 5 is -140935046558179200.00000000
Loss at epoch 6 is -641927310930069248.00000000
Loss at epoch 7 is -2922790958536478208.00000000
Loss at epoch 8 is -13308942107049345024.00000000
Loss at epoch 9 is -60605642770231787520.00000000
[[-1.87345582]
 [-1.3567729 ]
 [ 7.85496022]
 [-1.82839369]
 [ 7.02108315]
 [-1.23206356]
 [-0.86160177]]
(7, 1)
[[[22.01548722]]

 [[22.01548722]]

 [[22.01548722]]]
[[0.]
 [0.]
 [0.]]
[[-0.98973823]
 [-0.79030296]
 [-0.52119322]
 [-1.26007697]
 [-2.13049329]
 [-0.91291899]
 [ 6.4045555 ]]
(7, 1)
[[[22.01548722]]

 [[22.01548722]]

 [[22.01548722]]]
[[0.]
 [0.]
 [0.]]
[[-1.82750464]
 [-1.56041956]
 [-1.63605806]
 [-0.60528458]
 [-1.51682826]
 [-1.31446494]
 [-1.34209656]]
(7, 1)
[[[

/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:954: RuntimeWarning: divide by zero encountered in log
  log_A = np.log(self.transmat_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:957: RuntimeWarning: divide by zero encountered in log
  log_pi = np.log(self.startprob_)

Fit model:  25%|███████████████████████████████████████                                                                                                                     | 5/20 [00:01<00:03,  4.78it/s]/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:954: RuntimeWarning: divide by zero encountered in log
  log_A = np.log(self.transmat_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:957: RuntimeWarning: divide by zero encountered in log
  log_pi = np.log(self.startprob_)
/ziob/klaudi

(8, 7, 3)
(8, 7, 3)
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]
(8, 7, 3)
(8, 7, 3)
[[0.]
 [0.]
 [0.]]
Loss at epoch 0 is -26758741642951277594183467008.00000000
Loss at epoch 1 is -189865582724657068347140079616.00000000
Loss at epoch 2 is -1359051280975466266250908270592.00000000
Loss at epoch 3 is -9709099064026734432506892779520.00000000
Loss at epoch 4 is -

/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:954: RuntimeWarning: divide by zero encountered in log
  log_A = np.log(self.transmat_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:957: RuntimeWarning: divide by zero encountered in log
  log_pi = np.log(self.startprob_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:892: RuntimeWarning: divide by zero encountered in true_divide
  _covars_ = ((covars_prior + c_n) /
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:954: RuntimeWarning: divide by zero encountered in log
  log_A = np.log(self.transmat_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:957: RuntimeWarning: divide by zero encountered in log
  log_pi = np.log(self.startprob_)

Fit mode

(8, 7, 3)
(8, 7, 3)
[[0.]
 [0.]
 [0.]]
Loss at epoch 0 is -12976817500428843306390541003730714624.00000000
Loss at epoch 1 is -111594664037890784780711532435486015488.00000000
Loss at epoch 2 is -965598800432023895814492859555196698624.00000000
Loss at epoch 3 is -8345416851520522005139711336548642324480.00000000
Loss at epoch 4 is -72094547527012560118164346365478663356416.00000000
Loss at epoch 5 is -622874975069446783409083564879438185234432.00000000
Loss at epoch 6 is -5382210293877512520213612039310097571119104.00000000
Loss at epoch 7 is -46503362435104911379150555667982728854241280.00000000
Loss at epoch 8 is -401802470114348816235399138174987518187929600.00000000
Loss at epoch 9 is -3471700074215472496700297720962013816929910784.00000000
[[-1.87345582]
 [-1.3567729 ]
 [ 7.85496022]
 [-1.82839369]
 [ 7.02108315]
 [-1.23206356]
 [-0.86160177]]
(7, 1)
[[[22.01548722]]

 [[22.01548722]]

 [[22.01548722]]]
[[0.]
 [0.]
 [0.]]
[[-0.98973823]
 [-0.79030296]
 [-0.52119322]
 [-1.26007697

/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:892: RuntimeWarning: divide by zero encountered in true_divide
  _covars_ = ((covars_prior + c_n) /
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:954: RuntimeWarning: divide by zero encountered in log
  log_A = np.log(self.transmat_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:957: RuntimeWarning: divide by zero encountered in log
  log_pi = np.log(self.startprob_)

Fit model:  40%|██████████████████████████████████████████████████████████████▍                                                                                             | 8/20 [00:01<00:01,  6.05it/s]/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:954: RuntimeWarning: divide by zero encountered in log
  log_A = np.log(self.transmat_)
/z

[[-0.32663715]
 [ 5.51725098]
 [ 7.04671163]
 [-7.86424793]
 [ 7.76965919]
 [ 8.06176226]
 [ 6.97103327]]
(7, 1)
[[[22.01548722]]

 [[22.01548722]]

 [[22.01548722]]]
[[0.]
 [0.]
 [0.]]
[[-2.05603541]
 [-0.35187864]
 [-0.02752231]
 [-7.74541464]
 [-1.07828821]
 [-2.59434903]
 [ 0.44811754]]
(7, 1)
[[[22.01548722]]

 [[22.01548722]]

 [[22.01548722]]]
[[0.]
 [0.]
 [0.]]
(8, 7, 3)
(8, 7, 3)
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]
[[0. 1. 0.]
 

/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:954: RuntimeWarning: divide by zero encountered in log
  log_A = np.log(self.transmat_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:957: RuntimeWarning: divide by zero encountered in log
  log_pi = np.log(self.startprob_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:892: RuntimeWarning: divide by zero encountered in true_divide
  _covars_ = ((covars_prior + c_n) /
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:954: RuntimeWarning: divide by zero encountered in log
  log_A = np.log(self.transmat_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:957: RuntimeWarning: divide by zero encountered in log
  log_pi = np.log(self.startprob_)

Fit mode

(8, 7, 3)
(8, 7, 3)
[[0.]
 [0.]
 [0.]]
Loss at epoch 0 is -58658068205537867005298336903904825338453947136907953796702101569536.00000000
Loss at epoch 1 is -817477689578333908862427553976582002584234691274096298331509218082816.00000000
Loss at epoch 2 is -11421157409710830923436928406868716024386490227379662978711919739797504.00000000
Loss at epoch 3 is -159519094366075254553614067082022733081552557978115218388958520134336512.00000000
Loss at epoch 4 is -2227670505578856221476353526041677105243083235783471610708083999617581056.00000000
Loss at epoch 5 is -31109423869116473074276328195754977034837023445358590462685282942775721984.00000000
Loss at epoch 6 is -434464413940515676302094192874898601802994268791719876680214287594465263616.00000000
Loss at epoch 7 is -6067428102558147489148323284111885488888770812312424773066750918961831870464.00000000
Loss at epoch 8 is -84734211755961452741740510613943408473972320757442664044741220259704684412928.00000000
Loss at epoch 9 is -1183345100007819

/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:957: RuntimeWarning: divide by zero encountered in log
  log_pi = np.log(self.startprob_)

Fit model:  55%|█████████████████████████████████████████████████████████████████████████████████████▎                                                                     | 11/20 [00:02<00:01,  6.71it/s]/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:954: RuntimeWarning: divide by zero encountered in log
  log_A = np.log(self.transmat_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:957: RuntimeWarning: divide by zero encountered in log
  log_pi = np.log(self.startprob_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:892: RuntimeWarning: divide by zero encountered in true_divide
  _covars_ = ((covars_prior + c_n) /


(8, 7, 3)
(8, 7, 3)
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]
(8, 7, 3)
(8, 7, 3)
[[0.]
 [0.]
 [0.]]
Loss at epoch 0 is -28767057858635482276905798820839803947153134241129216455369741292697262142590113929716826112.00000000
Loss at epoch 1 is -523196811796723306670862542958301057603815608558850017658455939862175423801498065338743390208.00000000
Loss at epoch 2 

/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:954: RuntimeWarning: divide by zero encountered in log
  log_A = np.log(self.transmat_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:957: RuntimeWarning: divide by zero encountered in log
  log_pi = np.log(self.startprob_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:892: RuntimeWarning: divide by zero encountered in true_divide
  _covars_ = ((covars_prior + c_n) /
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:954: RuntimeWarning: divide by zero encountered in log
  log_A = np.log(self.transmat_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:957: RuntimeWarning: divide by zero encountered in log
  log_pi = np.log(self.startprob_)

Fit mode

(8, 7, 3)
(8, 7, 3)
[[0.]
 [0.]
 [0.]]
Loss at epoch 0 is -140994588830682928887214646570528241001103819461556658540131515037759446470718420091199050744550760906752.00000000
Loss at epoch 1 is -2893520860871069605471882316117318600267650403034489827408306801109306323401996787161130287070027010015232.00000000
Loss at epoch 2 is -59452416217755128246732738493337111498410138822617925623603087946926713272050415546116779605829991140425728.00000000
Loss at epoch 3 is -1221429312304900591457230034380857953612787834973754303495642236942432113421224516684006750173418137533284352.00000000
Loss at epoch 4 is -25092424935014029164605419363065212033158875356548479973497776824671155291387670270043764910057474592440582144.00000000
Loss at epoch 5 is -515485291844912058248507250236857863238145387426181055451554099658908447738973529279146660097466674742638411776.00000000
Loss at epoch 6 is -10590039843340023443219467404076375730626309002631977411979937726785681754006410437851588518663236904970434379776

/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:954: RuntimeWarning: divide by zero encountered in log
  log_A = np.log(self.transmat_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:957: RuntimeWarning: divide by zero encountered in log
  log_pi = np.log(self.startprob_)

Fit model:  70%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                              | 14/20 [00:02<00:00,  6.31it/s]/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:954: RuntimeWarning: divide by zero encountered in log
  log_A = np.log(self.transmat_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:957: RuntimeWarning: divide by zero encountered in log
  log_pi = np.log(self.startprob_)
/ziob/klaudi

[[-1.09713147]
 [ 7.48857674]
 [-0.13672663]
 [-1.22131061]
 [ 0.25887364]
 [ 0.39231698]
 [ 6.64762793]]
(7, 1)
[[[22.01548722]]

 [[22.01548722]]

 [[22.01548722]]]
[[0.]
 [0.]
 [0.]]
[[-0.32663715]
 [ 5.51725098]
 [ 7.04671163]
 [-7.86424793]
 [ 7.76965919]
 [ 8.06176226]
 [ 6.97103327]]
(7, 1)
[[[22.01548722]]

 [[22.01548722]]

 [[22.01548722]]]
[[0.]
 [0.]
 [0.]]
[[-2.05603541]
 [-0.35187864]
 [-0.02752231]
 [-7.74541464]
 [-1.07828821]
 [-2.59434903]
 [ 0.44811754]]
(7, 1)
[[[22.01548722]]

 [[22.01548722]]

 [[22.01548722]]]
[[0.]
 [0.]
 [0.]]
(8, 7, 3)
(8, 7, 3)
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.

/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:954: RuntimeWarning: divide by zero encountered in log
  log_A = np.log(self.transmat_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:957: RuntimeWarning: divide by zero encountered in log
  log_pi = np.log(self.startprob_)

Fit model:  75%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                      | 15/20 [00:02<00:00,  6.17it/s]/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:954: RuntimeWarning: divide by zero encountered in log
  log_A = np.log(self.transmat_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:957: RuntimeWarning: divide by zero encountered in log
  log_pi = np.log(self.startprob_)
/ziob/klaudi

(8, 7, 3)
(8, 7, 3)
[[0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]]
(8, 7, 3)
(8, 7, 3)
[[0.]
 [0.]
 [0.]]
Loss at epoch 0 is -16382544211567462101174964561622126338290714402267220588615420250506061895235349919651117970337861944517094774818251213513126670228460438407872512.00000000
Loss at epoch 1 is -46473842068055757826714889666213996871415210846991314443072298577

/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:954: RuntimeWarning: divide by zero encountered in log
  log_A = np.log(self.transmat_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:957: RuntimeWarning: divide by zero encountered in log
  log_pi = np.log(self.startprob_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:892: RuntimeWarning: divide by zero encountered in true_divide
  _covars_ = ((covars_prior + c_n) /
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:954: RuntimeWarning: divide by zero encountered in log
  log_A = np.log(self.transmat_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:957: RuntimeWarning: divide by zero encountered in log
  log_pi = np.log(self.startprob_)

Fit mode

(8, 7, 3)
(8, 7, 3)
[[0.]
 [0.]
 [0.]]
Loss at epoch 0 is -6511738235472402287798912309284781934133523992744317655677676983084313432700116436327657875889744873238721482829766892418682515929661715436442359846026138877952.00000000
Loss at epoch 1 is -203584948828127339874282332341693949203364129733935097260844976647127133241308431183629881778825638942184591361181483132176578247646076706675701656696540694052864.00000000
Loss at epoch 2 is -6368304825182094002676632420930830015285898555733918492450423045119093571540151376917414301353780415051823906760725130568234604153728764645080864849937307912896512.00000000
Loss at epoch 3 is -199199767644580899874247556443974855556051680349762760745104148088274210387718007631843399834901822937227620562033972741069063667305173146830670898577369355293556736.00000000
Loss at epoch 4 is -6230826163388826399497399540801306037075056660279479950255220849861828132212297492741262413049507294453026530316522348939894621845395940398043256277131090654750834688.0000

/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:892: RuntimeWarning: divide by zero encountered in true_divide
  _covars_ = ((covars_prior + c_n) /
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:954: RuntimeWarning: divide by zero encountered in log
  log_A = np.log(self.transmat_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:957: RuntimeWarning: divide by zero encountered in log
  log_pi = np.log(self.startprob_)

Fit model:  90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌               | 18/20 [00:03<00:00,  6.40it/s]/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:954: RuntimeWarning: divide by zero encountered in log
  log_A = np.log(self.transmat_)
/z

(8, 7, 3)
(8, 7, 3)
[[0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]]
(8, 7, 3)
(8, 7, 3)
[[0.]
 [0.]
 [0.]]
Loss at epoch 0 is -17712078116683106919977402820594556944635238064844854673496139385887565244368281167424711582932946796659073280919982655692257333667475089595068456907534041442126305900781718630563726988673024.00000000
Loss at epoch 1 is -66384755008143510723

/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:954: RuntimeWarning: divide by zero encountered in log
  log_A = np.log(self.transmat_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:957: RuntimeWarning: divide by zero encountered in log
  log_pi = np.log(self.startprob_)

Fit model: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:03<00:00,  5.37it/s]
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:954: RuntimeWarning: divide by zero encountered in log
  log_A = np.log(self.transmat_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:957: RuntimeWarning: divide by zero encountered in log
  log_pi = np.log(self.startprob_)


Loss at epoch 3 is -7570874646371920680854747271479156199489783695753279519448922199206864491350183833006995162796037899785961611256983939252290638797998206227577185182190109741735398141741470109153705685055079304691875040045563904.00000000
Loss at epoch 4 is -308977264835832242561032216658847111223584683535445599776631418357348378633348466661751340998165983622531472072040904377029097399395392734876557647756945015858692462144018007191262790606729960400107330878169939968.00000000
Loss at epoch 5 is -12609755956632742266957387800960900712105097013562306580999071970638457792265958427176088744078348711769584601820927746560258259529882324870002114984044138173599880606300620558379007714535262307154355561011693486080.00000000
Loss at epoch 6 is -514621458176029721944031149866828575804461123842963778995764766854182929499672877398764538542667050339983019552546600328220851374909182587509552974643684021989439760910152885535100967812525160451708896463271225196544.00000000
Loss at epoch 7 is -21002

Fit model:   0%|                                                                                                                                                                    | 0/20 [00:00<?, ?it/s]

[[-1.87345582]
 [-1.3567729 ]
 [ 7.85496022]
 [-1.82839369]
 [ 7.02108315]
 [-1.23206356]
 [-0.86160177]]
(7, 1)
[[[22.01548722]]

 [[22.01548722]]

 [[22.01548722]]]
[[-1.0654756 ]
 [ 7.03192772]
 [-7.33090193]]
[[-0.98973823]
 [-0.79030296]
 [-0.52119322]
 [-1.26007697]
 [-2.13049329]
 [-0.91291899]
 [ 6.4045555 ]]
(7, 1)
[[[22.01548722]]

 [[22.01548722]]

 [[22.01548722]]]
[[-1.0654756 ]
 [ 7.03192772]
 [-7.33090193]]
[[-1.82750464]
 [-1.56041956]
 [-1.63605806]
 [-0.60528458]
 [-1.51682826]
 [-1.31446494]
 [-1.34209656]]
(7, 1)
[[[22.01548722]]

 [[22.01548722]]

 [[22.01548722]]]
[[-1.0654756 ]
 [ 7.03192772]
 [-7.33090193]]
[[-1.24947708]
 [ 5.00654833]
 [ 7.08869017]
 [-5.14216167]
 [-9.18718354]
 [ 6.57960094]
 [-6.79793569]]
(7, 1)
[[[22.01548722]]

 [[22.01548722]]

 [[22.01548722]]]
[[-1.0654756 ]
 [ 7.03192772]
 [-7.33090193]]
[[-7.24846813]
 [ 8.60814797]
 [-0.60699331]
 [ 7.29002797]
 [-1.95398524]
 [ 7.01100108]
 [ 7.17553396]]
(7, 1)
[[[22.01548722]]

 [[22.01548722]]


/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:892: RuntimeWarning: divide by zero encountered in true_divide
  _covars_ = ((covars_prior + c_n) /

Fit model:   5%|███████▊                                                                                                                                                    | 1/20 [00:00<00:16,  1.17it/s]/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:892: RuntimeWarning: divide by zero encountered in true_divide
  _covars_ = ((covars_prior + c_n) /
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:957: RuntimeWarning: divide by zero encountered in log
  log_pi = np.log(self.startprob_)

Fit model:  10%|███████████████▌                                                                                                                                            | 2/20 [00:0

Loss at epoch 0 is 76.41514311
Loss at epoch 1 is 74.21043638
Loss at epoch 2 is 70.99191420
Loss at epoch 3 is 65.68771454
Loss at epoch 4 is 56.64981610
Loss at epoch 5 is 41.16694666
Loss at epoch 6 is 14.73780765
Loss at epoch 7 is -30.39625291
Loss at epoch 8 is -107.60037657
Loss at epoch 9 is -239.58923771
[[-1.87345582]
 [-1.3567729 ]
 [ 7.85496022]
 [-1.82839369]
 [ 7.02108315]
 [-1.23206356]
 [-0.86160177]]
(7, 1)
[[[22.01548722]]

 [[22.01548722]]

 [[22.01548722]]]
[[0.]
 [0.]
 [0.]]
[[-0.98973823]
 [-0.79030296]
 [-0.52119322]
 [-1.26007697]
 [-2.13049329]
 [-0.91291899]
 [ 6.4045555 ]]
(7, 1)
[[[22.01548722]]

 [[22.01548722]]

 [[22.01548722]]]
[[0.]
 [0.]
 [0.]]
[[-1.82750464]
 [-1.56041956]
 [-1.63605806]
 [-0.60528458]
 [-1.51682826]
 [-1.31446494]
 [-1.34209656]]
(7, 1)
[[[22.01548722]]

 [[22.01548722]]

 [[22.01548722]]]
[[0.]
 [0.]
 [0.]]
[[-1.24947708]
 [ 5.00654833]
 [ 7.08869017]
 [-5.14216167]
 [-9.18718354]
 [ 6.57960094]
 [-6.79793569]]
(7, 1)
[[[22.01548722

/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:957: RuntimeWarning: divide by zero encountered in log
  log_pi = np.log(self.startprob_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:892: RuntimeWarning: divide by zero encountered in true_divide
  _covars_ = ((covars_prior + c_n) /
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:954: RuntimeWarning: divide by zero encountered in log
  log_A = np.log(self.transmat_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:957: RuntimeWarning: divide by zero encountered in log
  log_pi = np.log(self.startprob_)

Fit model:  15%|███████████████████████▍                                                                                                                                    | 3/20 [00:01<00:05,  3.37it/s]

[[0.00000000e+000 0.00000000e+000 1.00000000e+000]
 [1.00000000e+000 2.51367878e-086 5.47798411e-141]
 [2.51367878e-086 5.09774101e-047 1.00000000e+000]
 [1.00000000e+000 2.51367878e-086 2.51367878e-086]
 [5.02735757e-086 5.09774101e-047 1.00000000e+000]
 [1.00000000e+000 2.51367878e-086 5.02735757e-086]
 [7.54103635e-086 5.09774101e-047 1.00000000e+000]]
[[0.00000000e+000 0.00000000e+000 1.00000000e+000]
 [1.00000000e+000 2.51367878e-086 5.47798411e-141]
 [2.51367878e-086 5.09774101e-047 1.00000000e+000]
 [1.00000000e+000 2.51367878e-086 2.51367878e-086]
 [5.02735757e-086 5.09774101e-047 1.00000000e+000]
 [1.00000000e+000 2.51367878e-086 5.02735757e-086]
 [7.54103635e-086 5.09774101e-047 1.00000000e+000]]
[[0.00000000e+000 0.00000000e+000 1.00000000e+000]
 [1.00000000e+000 2.51367878e-086 5.47798411e-141]
 [2.51367878e-086 5.09774101e-047 1.00000000e+000]
 [1.00000000e+000 2.51367878e-086 2.51367878e-086]
 [5.02735757e-086 5.09774101e-047 1.00000000e+000]
 [1.00000000e+000 2.51367878e

/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:892: RuntimeWarning: divide by zero encountered in true_divide
  _covars_ = ((covars_prior + c_n) /
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:954: RuntimeWarning: divide by zero encountered in log
  log_A = np.log(self.transmat_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:957: RuntimeWarning: divide by zero encountered in log
  log_pi = np.log(self.startprob_)

Fit model:  20%|███████████████████████████████▏                                                                                                                            | 4/20 [00:01<00:03,  4.08it/s]/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:954: RuntimeWarning: divide by zero encountered in log
  log_A = np.log(self.transmat_)
/z

Loss at epoch 7 is -530783555207521792.00000000
Loss at epoch 8 is -2416925364028566528.00000000
Loss at epoch 9 is -11006082540393164800.00000000
[[-1.87345582]
 [-1.3567729 ]
 [ 7.85496022]
 [-1.82839369]
 [ 7.02108315]
 [-1.23206356]
 [-0.86160177]]
(7, 1)
[[[22.01548722]]

 [[22.01548722]]

 [[22.01548722]]]
[[0.]
 [0.]
 [0.]]
[[-0.98973823]
 [-0.79030296]
 [-0.52119322]
 [-1.26007697]
 [-2.13049329]
 [-0.91291899]
 [ 6.4045555 ]]
(7, 1)
[[[22.01548722]]

 [[22.01548722]]

 [[22.01548722]]]
[[0.]
 [0.]
 [0.]]
[[-1.82750464]
 [-1.56041956]
 [-1.63605806]
 [-0.60528458]
 [-1.51682826]
 [-1.31446494]
 [-1.34209656]]
(7, 1)
[[[22.01548722]]

 [[22.01548722]]

 [[22.01548722]]]
[[0.]
 [0.]
 [0.]]
[[-1.24947708]
 [ 5.00654833]
 [ 7.08869017]
 [-5.14216167]
 [-9.18718354]
 [ 6.57960094]
 [-6.79793569]]
(7, 1)
[[[22.01548722]]

 [[22.01548722]]

 [[22.01548722]]]
[[0.]
 [0.]
 [0.]]
[[-7.24846813]
 [ 8.60814797]
 [-0.60699331]
 [ 7.29002797]
 [-1.95398524]
 [ 7.01100108]
 [ 7.17553396]]
(7,

/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:957: RuntimeWarning: divide by zero encountered in log
  log_pi = np.log(self.startprob_)

Fit model:  25%|███████████████████████████████████████                                                                                                                     | 5/20 [00:01<00:03,  4.61it/s]/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:954: RuntimeWarning: divide by zero encountered in log
  log_A = np.log(self.transmat_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:957: RuntimeWarning: divide by zero encountered in log
  log_pi = np.log(self.startprob_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:892: RuntimeWarning: divide by zero encountered in true_divide
  _covars_ = ((covars_prior + c_n) /


[[0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]]
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]]
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]]
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]]
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]]
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]]
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]]
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]]
(8, 7, 3)
(8, 7, 3)
[[0.]
 [0.]
 [0.]]
Loss at epoch 0 is -4859430668410992552000356352.00000000
Loss at epoch 1 is -34479896247697019347201425408.00000000
Loss at epoch 2 is -246805906003984278260589527040.00000000
Loss at epoch 3 is -1763188059584950127149963018240.00000000
Loss at epoch 4 is -12587627715402177792791

/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:957: RuntimeWarning: divide by zero encountered in log
  log_pi = np.log(self.startprob_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:892: RuntimeWarning: divide by zero encountered in true_divide
  _covars_ = ((covars_prior + c_n) /
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:954: RuntimeWarning: divide by zero encountered in log
  log_A = np.log(self.transmat_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:957: RuntimeWarning: divide by zero encountered in log
  log_pi = np.log(self.startprob_)

Fit model:  35%|██████████████████████████████████████████████████████▌                                                                                                     | 7/20 [00:01<00:02,  5.31it/s]

(8, 7, 3)
(8, 7, 3)
[[0.]
 [0.]
 [0.]]
Loss at epoch 0 is -2356611001420729887247903417503318016.00000000
Loss at epoch 1 is -20265771092400191535550296380160344064.00000000
Loss at epoch 2 is -175354300542607457647012159561765224448.00000000
Loss at epoch 3 is -1515541168941096737369623552683491196928.00000000
Loss at epoch 4 is -13092486184612891781652991167424934969344.00000000
Loss at epoch 5 is -113115100733273950149876495123265173323776.00000000
Loss at epoch 6 is -977418075741027008253493011351387578040320.00000000
Loss at epoch 7 is -8445085670196263434329029282346445507133440.00000000
Loss at epoch 8 is -72967977043539885486993028028562789743198208.00000000
Loss at epoch 9 is -630466336469552413331404594595566917850759168.00000000
[[-1.87345582]
 [-1.3567729 ]
 [ 7.85496022]
 [-1.82839369]
 [ 7.02108315]
 [-1.23206356]
 [-0.86160177]]
(7, 1)
[[[22.01548722]]

 [[22.01548722]]

 [[22.01548722]]]
[[0.]
 [0.]
 [0.]]
[[-0.98973823]
 [-0.79030296]
 [-0.52119322]
 [-1.26007697]
 [-2

/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:954: RuntimeWarning: divide by zero encountered in log
  log_A = np.log(self.transmat_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:957: RuntimeWarning: divide by zero encountered in log
  log_pi = np.log(self.startprob_)

Fit model:  40%|██████████████████████████████████████████████████████████████▍                                                                                             | 8/20 [00:01<00:02,  5.57it/s]/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:954: RuntimeWarning: divide by zero encountered in log
  log_A = np.log(self.transmat_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:957: RuntimeWarning: divide by zero encountered in log
  log_pi = np.log(self.startprob_)
/ziob/klaudi

(8, 7, 3)
(8, 7, 3)
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]]
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]]
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]]
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]]
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]]
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]]
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]]
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]]
(8, 7, 3)
(8, 7, 3)
[[0.]
 [0.]
 [0.]]
Loss at epoch 0 is -128163192228682098939019873578246870351646813124672094208.00000000
Loss at epoch 1 is -1540431336816583021136717936785173365525610280209971412992.00000000
Loss at epoch 2 is -18576211599315137484837096657081161548584192404242716164096.000000

/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:892: RuntimeWarning: divide by zero encountered in true_divide
  _covars_ = ((covars_prior + c_n) /
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:954: RuntimeWarning: divide by zero encountered in log
  log_A = np.log(self.transmat_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:957: RuntimeWarning: divide by zero encountered in log
  log_pi = np.log(self.startprob_)

Fit model:  50%|█████████████████████████████████████████████████████████████████████████████▌                                                                             | 10/20 [00:02<00:01,  6.48it/s]/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:954: RuntimeWarning: divide by zero encountered in log
  log_A = np.log(self.transmat_)
/z

[[0.]
 [0.]
 [0.]]
Loss at epoch 0 is -10652399854639972073132509683218440971613292077306270101671522598912.00000000
Loss at epoch 1 is -148455267758264592870227041107793070556213802568505538026114031550464.00000000
Loss at epoch 2 is -2074100618259668964777323646509566933354895360366784953314596389650432.00000000
Loss at epoch 3 is -28968924985447361484718925944771903888430663768401584811559982439858176.00000000
Loss at epoch 4 is -404548559060348094180803602869542539825557449241735773445656589830717440.00000000
Loss at epoch 5 is -5649521582267577028896769138611593848069190978219298075709928288104218624.00000000
Loss at epoch 6 is -78899438755626366167969698557401653226562339328377013358683236480453705728.00000000
Loss at epoch 7 is -1101854735673462967765326063723776198192933028429164258591905192160144654336.00000000
Loss at epoch 8 is -15387869607799676255981835893560966588643308938904328366670497135230034378752.00000000
Loss at epoch 9 is -21489737996728209917813899354474937890496

/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:954: RuntimeWarning: divide by zero encountered in log
  log_A = np.log(self.transmat_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:957: RuntimeWarning: divide by zero encountered in log
  log_pi = np.log(self.startprob_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:892: RuntimeWarning: divide by zero encountered in true_divide
  _covars_ = ((covars_prior + c_n) /
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:954: RuntimeWarning: divide by zero encountered in log
  log_A = np.log(self.transmat_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:957: RuntimeWarning: divide by zero encountered in log
  log_pi = np.log(self.startprob_)

Fit mode

(8, 7, 3)
(8, 7, 3)
[[0.]
 [0.]
 [0.]]
Loss at epoch 0 is -5224144134409407325336923801022251553063748645479636312290572806196185889842764895745998848.00000000
Loss at epoch 1 is -95013385411920682621285647447072180766156173039670881674545202714164366503147924184616665088.00000000
Loss at epoch 2 is -1730647128522856589877048001118513976589073480025066831589523673263024953014082626277624250368.00000000
Loss at epoch 3 is -31518834462884702634956667706374110861332180707598152130729255580631071384847540774473509634048.00000000
Loss at epoch 4 is -573982245185854552126096710010078914949954202178148382010973130102566874837620237709790907727872.00000000
Loss at epoch 5 is -10452650957056511910572188393367550869070667857464910746587874050007601599549698841553379644145664.00000000
Loss at epoch 6 is -190355351378360704209389223248799136847025290959077686740105606963791836461361936772293130832576512.00000000
Loss at epoch 7 is -346655099249239043128464853554745425058496438753721232533891956797

/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:954: RuntimeWarning: divide by zero encountered in log
  log_A = np.log(self.transmat_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:957: RuntimeWarning: divide by zero encountered in log
  log_pi = np.log(self.startprob_)

Fit model:  65%|████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                      | 13/20 [00:02<00:01,  6.72it/s]/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:954: RuntimeWarning: divide by zero encountered in log
  log_A = np.log(self.transmat_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:957: RuntimeWarning: divide by zero encountered in log
  log_pi = np.log(self.startprob_)
/ziob/klaudi

[[-0.32663715]
 [ 5.51725098]
 [ 7.04671163]
 [-7.86424793]
 [ 7.76965919]
 [ 8.06176226]
 [ 6.97103327]]
(7, 1)
[[[22.01548722]]

 [[22.01548722]]

 [[22.01548722]]]
[[0.]
 [0.]
 [0.]]
[[-2.05603541]
 [-0.35187864]
 [-0.02752231]
 [-7.74541464]
 [-1.07828821]
 [-2.59434903]
 [ 0.44811754]]
(7, 1)
[[[22.01548722]]

 [[22.01548722]]

 [[22.01548722]]]
[[0.]
 [0.]
 [0.]]
(8, 7, 3)
(8, 7, 3)
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
[[1. 0. 0.]
 

/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:954: RuntimeWarning: divide by zero encountered in log
  log_A = np.log(self.transmat_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:957: RuntimeWarning: divide by zero encountered in log
  log_pi = np.log(self.startprob_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:892: RuntimeWarning: divide by zero encountered in true_divide
  _covars_ = ((covars_prior + c_n) /
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:954: RuntimeWarning: divide by zero encountered in log
  log_A = np.log(self.transmat_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:957: RuntimeWarning: divide by zero encountered in log
  log_pi = np.log(self.startprob_)

Fit mode

(8, 7, 3)
(8, 7, 3)
[[0.]
 [0.]
 [0.]]
Loss at epoch 0 is -20589132813674467284286279982456863690705093076536139651016550195750620997023884490745389767284546164822647133000585678419985956864.00000000
Loss at epoch 1 is -527333560207913531989285706615617615450391110404227565459488247407051327285417606860137518972299085803927773088239371791499826036736.00000000
Loss at epoch 2 is -13516706411513741762704808466448974646813108329513036261728573155576743597945204251505182265139048661524008581699761851660446315053056.00000000
Loss at epoch 3 is -346443928795490808786293653976512311535259436571349985384241797891780996653173374501397050587112543704106541779112281332053603218620416.00000000
Loss at epoch 4 is -8879350274374124399729421697901929585590995490675246106260518792293166111751695282682445789187480364304056166822994712256645447083360256.00000000
Loss at epoch 5 is -227577190555416393296919411812058020908445048135221493299343280826449897909536678998280440971470376980920392207716593926247


Fit model:  80%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                               | 16/20 [00:03<00:00,  7.33it/s]/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:954: RuntimeWarning: divide by zero encountered in log
  log_A = np.log(self.transmat_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:957: RuntimeWarning: divide by zero encountered in log
  log_pi = np.log(self.startprob_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:892: RuntimeWarning: divide by zero encountered in true_divide
  _covars_ = ((covars_prior + c_n) /
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:954: RuntimeWarning: divide by zero encountered in log
  log_A = np.log(self.transmat_)
/z

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
(8, 7, 3)
(8, 7, 3)
[[0.]
 [0.]
 [0.]]
Loss at epoch 0 is -1182542172884761159522617043237878653450625962557857102810388818913679190204551274758416378495955255418042907918559027299598025056620083685443062740347818868736.00000000
Loss at epoch 1 is -36971355273832089957258604043494291551464833892364834270626151970377857

/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:954: RuntimeWarning: divide by zero encountered in log
  log_A = np.log(self.transmat_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:957: RuntimeWarning: divide by zero encountered in log
  log_pi = np.log(self.startprob_)

Fit model:  90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌               | 18/20 [00:03<00:00,  7.63it/s]/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:954: RuntimeWarning: divide by zero encountered in log
  log_A = np.log(self.transmat_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:957: RuntimeWarning: divide by zero encountered in log
  log_pi = np.log(self.startprob_)
/ziob/klaudi

[[-7.24846813]
 [ 8.60814797]
 [-0.60699331]
 [ 7.29002797]
 [-1.95398524]
 [ 7.01100108]
 [ 7.17553396]]
(7, 1)
[[[22.01548722]]

 [[22.01548722]]

 [[22.01548722]]]
[[0.]
 [0.]
 [0.]]
[[-1.09713147]
 [ 7.48857674]
 [-0.13672663]
 [-1.22131061]
 [ 0.25887364]
 [ 0.39231698]
 [ 6.64762793]]
(7, 1)
[[[22.01548722]]

 [[22.01548722]]

 [[22.01548722]]]
[[0.]
 [0.]
 [0.]]
[[-0.32663715]
 [ 5.51725098]
 [ 7.04671163]
 [-7.86424793]
 [ 7.76965919]
 [ 8.06176226]
 [ 6.97103327]]
(7, 1)
[[[22.01548722]]

 [[22.01548722]]

 [[22.01548722]]]
[[0.]
 [0.]
 [0.]]
[[-2.05603541]
 [-0.35187864]
 [-0.02752231]
 [-7.74541464]
 [-1.07828821]
 [-2.59434903]
 [ 0.44811754]]
(7, 1)
[[[22.01548722]]

 [[22.01548722]]

 [[22.01548722]]]
[[0.]
 [0.]
 [0.]]
(8, 7, 3)
(8, 7, 3)
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0

/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:954: RuntimeWarning: divide by zero encountered in log
  log_A = np.log(self.transmat_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:957: RuntimeWarning: divide by zero encountered in log
  log_pi = np.log(self.startprob_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:892: RuntimeWarning: divide by zero encountered in true_divide
  _covars_ = ((covars_prior + c_n) /
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:954: RuntimeWarning: divide by zero encountered in log
  log_A = np.log(self.transmat_)
/ziob/klaudia/recommender_system/src/models/gaussian_dense_hmm/dense-hmm/code_dense_hmm/models_gaussian.py:957: RuntimeWarning: divide by zero encountered in log
  log_pi = np.log(self.startprob_)

Fit mode

(8, 7, 3)
(8, 7, 3)
[[0.]
 [0.]
 [0.]]
Loss at epoch 0 is -20231889805451013548415468830798132692934127550896058655451723179872284360614506516110814306686220820105954406601520483969098472952083561442149335820357607359337474083492132099050394925050919722054999605248.00000000
Loss at epoch 1 is -825449901662167629143768283705928194739361450412616749676613103908780018424740083434284222637873236228823957138373406873932508372616362646685807900827932703669206751369499628572718312836387344988476499034112.00000000
Loss at epoch 2 is -33688470785202150554739925947755398225563700251779361265746284699588187209457744506823008172487745686198047281788897514995665294280431020550141056452420245402095729038959536901628170548203259478770657764835328.00000000
Loss at epoch 3 is -1374883054449030841796158737032227253821388145311890983852742787339103738369398300386986801504105334187687645152136839076762575488704622234831176179728700628799550164048792000461454326851371185830035059957039104.00000000
Loss at 

HMM: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:19<00:00,  6.36s/it]


In [10]:
# import tensorflow_probability as tfp
# tfd = tfp.distributions
# import tensorflow.compat.v1 as tf
# tf.disable_v2_behavior()
# x = np.array([[1, .9], [.9,  -1]])
# tf.keras.constraints.non_neg().__call__((x + x.transpose())  / 2)

In [11]:
res_tmp

{'standard_acc': [],
 'standard_time': [],
 'dense_acc': [0.5892857142857143, 0.5892857142857143, 0.5],
 'dense_time': [6.151768825948238, 6.298039370100014, 6.1235468469094485],
 'hmml_acc': [1.0, 1.0, 1.0],
 'hmml_time': [0.183921309071593, 0.12134284200146794, 0.2036114139482379],
 'pi': array([0.30828399, 0.17292231, 0.51879371]),
 'A': array([[0.30828399, 0.17292231, 0.51879371],
        [0.30828399, 0.17292231, 0.51879371],
        [0.30828399, 0.17292231, 0.51879371]]),
 'mu': array([ 7, -8, -1]),
 'sigma': array([0.70871082, 1.41094953, 0.82751029])}

In [ ]:
n=10
A_stat=False
T=20
s=5400
l=5
pi, A, mu, sigma = prepare_params(n, A_stat)
data = [my_hmm_sampler(pi, A, mu, sigma, T) for _ in range(s)]
X_true = np.concatenate([x[1] for x in data])
lenghts = [len(x[1]) for x in data]
Y_true = np.concatenate([np.concatenate(y[0]) for y in data])
print(X_true.shape)
standard_acc = []
standard_timer = []
dense_acc = []
dense_timer = []
hmml_acc = []
hmml_timer = []
# for _ in tqdm(range(10), desc="HMM"):
    # A_init = np.exp(np.random.uniform(0, 5, size=(n, n)))
    # A_init /= A_init.sum(axis=1)[:, np.newaxis]

start = time.perf_counter()
standardhmm = StandardGaussianHMM(n, em_iter=100, covariance_type='full')
# standardhmm.transmat_ = A_init
standardhmm.fit(X_true, lenghts)
preds = np.concatenate([standardhmm.predict(x[1]) for x in data])
standard_timer.append(time.perf_counter() - start)
perm = find_permutation(preds, Y_true)
standard_acc.append((Y_true == np.array([perm[i] for i in preds])).mean())
#
start = time.perf_counter()
densehmm = GaussianDenseHMM(n, init_params="",  em_iter=100,  mstep_config={"l_uz":  l, "l_vw": l,  "em_lr": 0.001, "em_epochs":5})
# densehmm.transmat_ = A_init
densehmm.fit(X_true, lenghts)
preds = np.concatenate([densehmm.predict(x[1]) for x in data])
perm = find_permutation(preds, Y_true)
dense_timer.append(time.perf_counter() - start)
dense_acc.append((Y_true == np.array([perm[i] for i in preds])).mean())

start = time.perf_counter()
hmml = hmm.GaussianHMM(n, n_iter=100, init_params="stmc")
# hmml.transmat_ = A_init
hmml.fit(X_true, lenghts)
preds = np.concatenate([hmml.predict(x[1]) for x in data])
hmml_timer.append(time.perf_counter() - start)
perm = find_permutation(preds, Y_true)
hmml_acc.append((Y_true == np.array([perm[i] for i in preds])).mean())

(108000, 1)


Fit model:   0%|                                                                                                                                                                   | 0/100 [00:00<?, ?it/s]

In [ ]:
print(standard_acc)
print(standard_timer)

print(dense_acc)
print(dense_timer)

print(hmml_acc)
print(hmml_timer)

In [13]:
standardhmm = StandardGaussianHMM(n, em_iter=3, covariance_type='diag', params='mc')
standardhmm._init(X_true, lenghts)
standardhmm._compute_log_likelihood(X_true)
self = standardhmm
lengths = lenghts
val=None
val_lengths=None
X, n_seqs, max_seqlen = self._init(X_true, lengths=lenghts)
self._check()
stats = self._initialize_sufficient_statistics(n_seqs, max_seqlen)
log_dict = self._compute_metrics(X, lengths, stats, iter, 'i', val, val_lengths)
stats, total_logprob = self._forward_backward_gamma_pass(X, lengths, stats)
log_dict = self._compute_metrics(X, lengths, stats, iter, 'aE', val, val_lengths)
print("MEANS", self.means_)
self._do_mstep(stats)
# stats
# self._compute_metrics(X, lengths, stats, iter, 'aM', val, val_lengths)

print("MEANS", self.means_)

Even though the 'startprob_' attribute is set, it will be overwritten during initialization because 'init_params' contains 's'
Even though the 'transmat_' attribute is set, it will be overwritten during initialization because 'init_params' contains 't'
Even though the 'means_' attribute is set, it will be overwritten during initialization because 'init_params' contains 'm'


[[[11.112556]]

 [[11.112556]]

 [[11.112556]]]
(440, 1)
[[-7.61828361]
 [ 9.22388749]
 [ 7.94295517]
 [ 6.12625367]
 [ 8.42252181]
 [ 7.1734648 ]
 [ 9.23655742]
 [ 6.26868342]
 [ 7.27187161]
 [ 5.05003119]
 [ 6.30797773]
 [ 7.1990105 ]
 [ 5.21122106]
 [ 5.6726165 ]
 [ 8.77026933]
 [ 6.74420216]
 [ 7.78833227]
 [ 6.20614357]
 [-9.08504554]
 [ 5.76908056]
 [ 7.12923272]
 [ 6.96935421]
 [ 7.07361153]
 [ 6.38069951]
 [ 6.14916964]
 [ 7.88098842]
 [ 8.84812386]
 [ 5.88696747]
 [ 5.77515578]
 [ 7.50177838]
 [ 6.35604658]
 [ 8.74761786]
 [ 5.90448133]
 [ 7.2348336 ]
 [ 8.40076803]
 [ 5.50444951]
 [ 7.56499685]
 [ 6.48694921]
 [ 8.66309025]
 [ 6.10927846]
 [ 8.58007144]
 [ 5.65336615]
 [ 7.81673496]
 [ 5.57789865]]
(44, 1)
[[[11.112556]]

 [[11.112556]]

 [[11.112556]]]
[[ 8.09530471]
 [-8.23061461]
 [ 6.06922338]]
[[ 7.20182437]
 [ 5.53685572]
 [ 7.98807369]
 [ 8.61415712]
 [ 6.82361942]
 [ 9.10281846]
 [ 6.48590459]
 [-7.67485371]
 [ 7.98678878]
 [ 6.75867778]
 [ 6.3001999 ]
 [ 6.3166031 ]


/ziob/klaudia/miniconda3/envs/hmm/lib/python3.10/site-packages/hmmlearn/hmm.py:272: RuntimeWarning: invalid value encountered in true_divide
  self.means_ = ((means_weight * means_prior + stats['obs'])
